# -*- coding: utf-8 -*-
"""Chat bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zgvoXo1rFk4Qif7oeZdzYVcUAUFLgiX8
"""

!pip install google-generativeai

import google.generativeai as genai
import json
import pathlib
import pprint
import  requests
from IPython.display import Markdown

from google.colab import userdata
API_KEY=userdata.get('Silviya')
genai.configure(api_key=API_KEY)

import google.generativeai as genai
generation_config={
    "temperature":0.9,
    "top_p":1,
    "top_k":1,
    "max_output_tokens":2048,
}
model=genai.GenerativeModel(model_name="gemini-pro",generation_config=generation_config,
                            )
prompt_parts=[
    input("Enter Your Prompt: "),
]
response=model.generate_content(prompt_parts,stream=False)

Markdown(response.text)

from IPython.display import Markdown

pip install pypdf

from pypdf import PdfReader
pdf = PdfReader('AWS developer guide.pdf')
text = ''
for page in pdf.pages:
  text += page.extract_text()
Markdown(text)

import google.generativeai as genai
generation_config={
    "temperature":0.9,
    "top_p":1,
    "top_k":1,
    "max_output_tokens":2048,
}
model=genai.GenerativeModel(model_name="gemini-pro",generation_config=generation_config,
                            )

prompt=input("Enter Your Prompt:")
responce=chat.send_message(f"{prompt},As per the above document")
Markdown(responce.text)

responce=chat.send_message(input("Enter Your Promt:"))
Markdown(responce.text)

chat=model.start_chat(history=[])
responce=chat.send_message(text)

chat.history